/*
 * DigitalRooster
 *
 * Open API for Digital Rooster
 *
 * API version: 1.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package digitalrooster

import (
	"encoding/json"
)

// Station struct for Station
type Station struct {
	Id *string `json:"id,omitempty"`
	Name string `json:"name"`
	Url string `json:"url"`
}

// NewStation instantiates a new Station object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStation(name string, url string, ) *Station {
	this := Station{}
	this.Name = name
	this.Url = url
	return &this
}

// NewStationWithDefaults instantiates a new Station object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStationWithDefaults() *Station {
	this := Station{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *Station) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Station) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *Station) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *Station) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value
func (o *Station) GetName() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *Station) GetNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *Station) SetName(v string) {
	o.Name = v
}

// GetUrl returns the Url field value
func (o *Station) GetUrl() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *Station) GetUrlOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *Station) SetUrl(v string) {
	o.Url = v
}

func (o Station) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if true {
		toSerialize["name"] = o.Name
	}
	if true {
		toSerialize["url"] = o.Url
	}
	return json.Marshal(toSerialize)
}

type NullableStation struct {
	value *Station
	isSet bool
}

func (v NullableStation) Get() *Station {
	return v.value
}

func (v *NullableStation) Set(val *Station) {
	v.value = val
	v.isSet = true
}

func (v NullableStation) IsSet() bool {
	return v.isSet
}

func (v *NullableStation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStation(val *Station) *NullableStation {
	return &NullableStation{value: val, isSet: true}
}

func (v NullableStation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


