/*
 * DigitalRooster
 *
 * Open API for Digital Rooster
 *
 * API version: 1.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package digitalrooster

import (
	"encoding/json"
)

// ResourceUuid struct for ResourceUuid
type ResourceUuid struct {
	// Uuid of created resource
	Id string `json:"id"`
}

// NewResourceUuid instantiates a new ResourceUuid object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResourceUuid(id string, ) *ResourceUuid {
	this := ResourceUuid{}
	this.Id = id
	return &this
}

// NewResourceUuidWithDefaults instantiates a new ResourceUuid object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResourceUuidWithDefaults() *ResourceUuid {
	this := ResourceUuid{}
	return &this
}

// GetId returns the Id field value
func (o *ResourceUuid) GetId() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ResourceUuid) GetIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ResourceUuid) SetId(v string) {
	o.Id = v
}

func (o ResourceUuid) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["id"] = o.Id
	}
	return json.Marshal(toSerialize)
}

type NullableResourceUuid struct {
	value *ResourceUuid
	isSet bool
}

func (v NullableResourceUuid) Get() *ResourceUuid {
	return v.value
}

func (v *NullableResourceUuid) Set(val *ResourceUuid) {
	v.value = val
	v.isSet = true
}

func (v NullableResourceUuid) IsSet() bool {
	return v.isSet
}

func (v *NullableResourceUuid) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResourceUuid(val *ResourceUuid) *NullableResourceUuid {
	return &NullableResourceUuid{value: val, isSet: true}
}

func (v NullableResourceUuid) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResourceUuid) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


